In [1]:
import pandas as pd

# Pandas
 is a python librairy based on

## Series
Series in Pandas can be Python Dict. Both of
them stored data in Key-Value data model,

In [2]:
series = pd.Series(data=[5, 6, 1, 0, 9, 2, 3], index=['a', 'b', 'c', 'd', 'e', 'f', 'gr'])
# in series index lenght and data lenght should be the same.

In [3]:
series

a     5
b     6
c     1
d     0
e     9
f     2
gr    3
dtype: int64

In [4]:
series.loc['a':'d'] # explicit index difined with type label

a    5
b    6
c    1
d    0
dtype: int64

In [5]:
series.iloc[:4] # implicit index is automatically created series[:4]

a    5
b    6
c    1
d    0
dtype: int64

In [6]:
series.info()

<class 'pandas.Series'>
Index: 7 entries, a to gr
Series name: None
Non-Null Count  Dtype
--------------  -----
7 non-null      int64
dtypes: int64(1)
memory usage: 420.0 bytes

In [7]:
series.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'gr'], dtype='str')

In [8]:
series.values

array([5, 6, 1, 0, 9, 2, 3])

In [9]:
series['e'] # get element by its explicit index

np.int64(9)

In [10]:
series[['a', 'e', 'gr']]

a     5
e     9
gr    3
dtype: int64

In [11]:
series[::2]

a     5
c     1
e     9
gr    3
dtype: int64

In [12]:
'a' in series

True

In [13]:
'l' in series

False

In [14]:
series.reindex(index=['a', 'b', 'c', 'd', 'e', 'gr', 'f'])

a     5
b     6
c     1
d     0
e     9
gr    3
f     2
dtype: int64

In [15]:
series.reindex(index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])
# if there's no corresponding value for an index NaN is assigned

a    5.0
b    6.0
c    1.0
d    0.0
e    9.0
f    2.0
g    NaN
dtype: float64

In [16]:
import numpy as np

In [17]:
A = np.arange(100)
A.resize((25, 4))

A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [18]:
df = pd.DataFrame(data=A)

df

     0   1   2   3
0    0   1   2   3
1    4   5   6   7
2    8   9  10  11
3   12  13  14  15
4   16  17  18  19
5   20  21  22  23
6   24  25  26  27
7   28  29  30  31
8   32  33  34  35
9   36  37  38  39
10  40  41  42  43
11  44  45  46  47
12  48  49  50  51
13  52  53  54  55
14  56  57  58  59
15  60  61  62  63
16  64  65  66  67
17  68  69  70  71
18  72  73  74  75
19  76  77  78  79
20  80  81  82  83
21  84  85  86  87
22  88  89  90  91
23  92  93  94  95
24  96  97  98  99

In [19]:
df.head()

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [20]:
df.tail()

     0   1   2   3
20  80  81  82  83
21  84  85  86  87
22  88  89  90  91
23  92  93  94  95
24  96  97  98  99

In [21]:
df.index

RangeIndex(start=0, stop=25, step=1)

In [22]:
df.index.size

25

In [23]:
df.columns

RangeIndex(start=0, stop=4, step=1)

In [24]:
df.columns.size

4

In [25]:
df.iloc[0, 0] # implicit

np.int64(0)

In [26]:
df.loc[4, 3] # explicit

np.int64(19)

We can create DataFrame from data file like csv, excel, sql file.....

In [28]:
csv_df = pd.read_csv('data/Churn_Modelling.csv', index_col='RowNumber')

FileNotFoundError: [Errno 2] No such file or directory: 'data/Churn_Modelling.csv'